import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { FooterComponent, HeaderComponent, FullFooterComponent, FullHeaderComponent, MainNavComponent, DownloadPDFComponent,ImageLoaderComponent, LogoutComponent, NoLinkFooterComponent,PrintComponent,OverviewLinkPipe, AddUserLinkPipe, UpdateUserLinkPipe, RemoveUserLinkPipe,LinkComponent,
    NoLinkHeaderComponent, PaginationComponent, ErrorComponent, CSVComponent, SubNavFullComponent, SortableColumnComponent, SubNavHalfComponent, ToolTipComponent, ProgressBarComponent, DatePickerComponent, ProgressStepComponent, StatusBoxComponent, LoadingComponent, ModalComponent, VUMLinkPipe, SDLMessageComponent, MessageComponent } from './index';
import { NotProvidedPipe, PhoneFormatPipe, PhoneExtnPipe, PhoneFormatPlaceHolderPipe, OnlyNumbersPipe, StripLeadingZeroPipe, NOwhiteSpacePipe, MaskBankAccountPipe } from '../_pipes'
import { SortService, PagerService, CSVService } from '../_services'
import { SortableTableDirective, OnlyNumbersDirective, NoWhiteSpacesDirective } from '../_directives'

@NgModule({
    imports: [ CommonModule, HttpModule, RouterModule, FormsModule ],
    declarations: [ FooterComponent,
                    HeaderComponent,
                    NoLinkFooterComponent,
                    NoLinkHeaderComponent,
                    FullFooterComponent,
                    FullHeaderComponent,
                    PaginationComponent,
                    ErrorComponent,
                    CSVComponent,
                    ProgressBarComponent,
                    ProgressStepComponent,
                    StatusBoxComponent,
                    LoadingComponent,
                    ModalComponent,
                    NotProvidedPipe,
                    PhoneFormatPipe,
                    PhoneExtnPipe,
                    PhoneFormatPlaceHolderPipe,
                    PrintComponent,
                    OverviewLinkPipe,
                    AddUserLinkPipe,
                    UpdateUserLinkPipe,
                    RemoveUserLinkPipe,
                    VUMLinkPipe,
                    OnlyNumbersPipe,
                    StripLeadingZeroPipe,
                    MaskBankAccountPipe,
                    NOwhiteSpacePipe,
                    SDLMessageComponent,
                    MessageComponent,
                    DownloadPDFComponent,
                    ImageLoaderComponent,
                    LogoutComponent,
                    DatePickerComponent,
                    ToolTipComponent,
                    MainNavComponent,
                    SubNavFullComponent,
                    SubNavHalfComponent,
                    ModalComponent,
                    SortableColumnComponent,
                    SortableTableDirective,
                    OnlyNumbersDirective,
                    NoWhiteSpacesDirective,
                    LinkComponent,
                  ],
    exports: [ FooterComponent,
               HeaderComponent,
               NoLinkFooterComponent,
               NoLinkHeaderComponent,
               FullFooterComponent,
               FullHeaderComponent,
               PaginationComponent,
               ErrorComponent,
               CSVComponent,
               ProgressBarComponent,
               StatusBoxComponent,
               LoadingComponent,
               ModalComponent,
               NotProvidedPipe,
               PhoneFormatPipe,
               PhoneExtnPipe,
               PhoneFormatPlaceHolderPipe,
               OnlyNumbersPipe,
               StripLeadingZeroPipe,
               NOwhiteSpacePipe,
               MaskBankAccountPipe,
               PrintComponent,
               SDLMessageComponent,
               MessageComponent,
               DownloadPDFComponent,
               ImageLoaderComponent,
               LogoutComponent,
               DatePickerComponent,
               ToolTipComponent,
               MainNavComponent,
               ModalComponent,
               SortableColumnComponent,
               SortableTableDirective,
               OnlyNumbersDirective,
               NoWhiteSpacesDirective,
               LinkComponent
             ],
    providers: [ SortService, PagerService, CSVService ]
})
export class SharedModule { }
